import { Inter } from "next/font/google";
import "./globals.css";
import SideNavbar from './SideNavbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className="flex ">
          <SideNavbar />
          <div className="flex-grow p-6">
            
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
